# Generated by Django 4.2.5 on 2025-03-16 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_appointment_patient_payment_tooth_toothcondition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.IntegerField(default=30)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_procedures', to='api.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='DentalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(blank=True, max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_conditions', to='api.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='DentalChartTooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('quadrant', models.CharField(choices=[('upper_right', 'Upper Right'), ('upper_left', 'Upper Left'), ('lower_right', 'Lower Right'), ('lower_left', 'Lower Left')], max_length=20)),
                ('type', models.CharField(choices=[('incisor', 'Incisor'), ('canine', 'Canine'), ('premolar', 'Premolar'), ('molar', 'Molar')], max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_chart_teeth', to='api.patient')),
            ],
            options={
                'unique_together': {('patient', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DentalChartProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('date_performed', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_dental_chart_procedures', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dentalprocedure')),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='api.dentalcharttooth')),
            ],
        ),
        migrations.CreateModel(
            name='DentalChartCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dentalcondition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dental_chart_conditions', to=settings.AUTH_USER_MODEL)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='api.dentalcharttooth')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_dental_chart_conditions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChartHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('add_condition', 'Add Condition'), ('update_condition', 'Update Condition'), ('remove_condition', 'Remove Condition'), ('add_procedure', 'Add Procedure'), ('update_procedure', 'Update Procedure'), ('cancel_procedure', 'Cancel Procedure')], max_length=20)),
                ('tooth_number', models.IntegerField()),
                ('details', models.JSONField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_history', to='api.patient')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
