# Generated by Django 4.2.5 on 2025-03-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dentalprocedure_dentalcondition_dentalcharttooth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='friday_hours',
            field=models.CharField(blank=True, default='09:00 - 17:00', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='monday_hours',
            field=models.CharField(blank=True, default='09:00 - 17:00', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='saturday_hours',
            field=models.CharField(blank=True, default='09:00 - 17:00', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='sunday_hours',
            field=models.CharField(blank=True, default='closed', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='thursday_hours',
            field=models.CharField(blank=True, default='09:00 - 17:00', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='tuesday_hours',
            field=models.CharField(blank=True, default='09:00 - 17:00', max_length=20),
        ),
        migrations.AddField(
            model_name='clinic',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='wednesday_hours',
            field=models.CharField(blank=True, default='09:00 - 17:00', max_length=20),
        ),
    ]
