# Generated by Django 4.2.5 on 2025-03-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clinic_friday_hours_clinic_monday_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='friday_hours',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='monday_hours',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='saturday_hours',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='sunday_hours',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='thursday_hours',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='tuesday_hours',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='website',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='wednesday_hours',
        ),
    ]
