# Generated by Django 4.2.5 on 2025-03-17 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_clinic_friday_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalcondition',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dentalcondition',
            name='is_standard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dentalprocedure',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dentalprocedure',
            name='is_standard',
            field=models.BooleanField(default=True),
        ),
    ]
