# Generated by Django 4.2.5 on 2025-03-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_standard_dental_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dentalcharttooth',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dentalcharttooth',
            name='dentition_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('primary', 'Primary')], default='permanent', max_length=10),
        ),
        migrations.AddField(
            model_name='dentalcharttooth',
            name='universal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentalcharttooth',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='dentalcharttooth',
            unique_together={('patient', 'number', 'dentition_type')},
        ),
        migrations.RemoveField(
            model_name='dentalcharttooth',
            name='type',
        ),
    ]
