# Generated by Django 4.2.5 on 2025-03-17 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_primaryteeth_backfill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charthistory',
            options={},
        ),
        migrations.AlterField(
            model_name='charthistory',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
        migrations.AlterField(
            model_name='charthistory',
            name='tooth_number',
            field=models.CharField(max_length=10),
        ),
    ]
