# Generated by Django 4.2.5 on 2025-03-18 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_alter_charthistory_options_alter_charthistory_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('appointment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-appointment_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='charthistory',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='charthistory',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='charthistory',
            name='action',
            field=models.CharField(choices=[('add_condition', 'Add Condition'), ('update_condition', 'Update Condition'), ('remove_condition', 'Remove Condition'), ('add_procedure', 'Add Procedure'), ('update_procedure', 'Update Procedure'), ('remove_procedure', 'Remove Procedure'), ('add_procedure_note', 'Add Procedure Note')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='charthistory',
            index=models.Index(fields=['patient', 'tooth_number'], name='api_charthi_patient_9915f5_idx'),
        ),
        migrations.AddIndex(
            model_name='charthistory',
            index=models.Index(fields=['patient', 'category'], name='api_charthi_patient_405e11_idx'),
        ),
        migrations.AddIndex(
            model_name='charthistory',
            index=models.Index(fields=['patient', 'date'], name='api_charthi_patient_fa918f_idx'),
        ),
        migrations.AddField(
            model_name='procedurenote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedurenote',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.dentalchartprocedure'),
        ),
    ]
