# Generated by Django 4.2.5 on 2025-03-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_procedurenote_alter_charthistory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentalchartprocedure',
            old_name='notes',
            new_name='description',
        ),
    ]
