# Generated by Django 4.2.5 on 2025-03-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_notes_dentalchartprocedure_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentalchartcondition',
            old_name='notes',
            new_name='description',
        ),
    ]
