# Generated by Django 4.2.5 on 2025-03-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_notes_dentalchartcondition_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dentalcharttooth',
            unique_together=set(),
        ),
    ]
