# Generated by Django 4.2.5 on 2025-03-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_dentalcharttooth_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dentalcharttooth',
            unique_together={('patient', 'number', 'dentition_type')},
        ),
        migrations.RemoveField(
            model_name='dentalcharttooth',
            name='universal_number',
        ),
    ]
