# Generated by Django 4.2.5 on 2025-03-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_dentalcharttooth_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalchartcondition',
            name='description',
        ),
        migrations.AddField(
            model_name='dentalchartcondition',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dentalcharttooth',
            name='universal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
