# Generated by Django 4.2.5 on 2025-03-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_dentalchartcondition_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentalchartcondition',
            name='notes',
        ),
        migrations.AddField(
            model_name='dentalchartcondition',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
