# Generated by Django 4.2.5 on 2025-03-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_generalprocedure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalprocedure',
            options={'ordering': ['-created_at']},
        ),
    ]
