# Generated by Django 4.2.5 on 2025-03-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_generalprocedurenote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalprocedure',
            old_name='notes',
            new_name='procedure_notes',
        ),
    ]
