# Generated by Django 4.2.5 on 2025-06-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_notes_generalprocedure_procedure_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentalchartcondition',
            name='date_detected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
